### ISSUE TITLE
TARDIS door hitbox issue and dematerialization/rematerialization speed issue

### ISSUE THREAD

**Issue by WhoWarz** [WhoCraft/TardisRefined#134]
### Issue description

when entering and exiting the "big ben" and "vending machine" tardis' the game acts as if there is a half slab in the way and does not let you enter unless the player is crouching. this can also cause the player to get trapped beneath the tardis floor. the secondary issue is with the speed of the tardis. ive found that when using a landing pad, the tardis materializing does not sync up with the audio unless you are using either the briefcase exterior or the growth. the other thing these two share in common is they are the only ones not to work with immersive portals. im not 100% sure if this is intentional or not

here is a video i have made documenting these issues: https://youtu.be/hy-x0oQp8oE

### Steps to reproduce

see video listed: https://youtu.be/hy-x0oQp8oE

(this link is the same as in the issue description)

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader Version 0.14.13-1.19.2

### Tardis Refined version

v1.0

**Comment by CommandrMoose** [comment]
Thanks for the report! We'll be looking into this over the coming week.

**Comment by thejudge156** [comment]
Curious, I thought I fixed that.
