### ISSUE TITLE
A superflat crash

### ISSUE THREAD

**Issue by DaPuffer** [WhoCraft/TardisRefined#142]
### Issue description

Attempting to Enter a newly placed root shell in a superflat world crashes the game

### Steps to reproduce

1.Place a root shell
2. Try to enter it
3. Look at the -1 exit code

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge Version 43.2.0

### Tardis Refined version

v1.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

[crash-2023-05-09_20.12.01-server.txt](https://github.com/CommandrMoose/TardisRefined/files/11432163/crash-2023-05-09_20.12.01-server.txt)

**Comment by thejudge156** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/8964

Might be related, appears to be a vanilla issue.

**Comment by CommandrMoose** [comment]
For current developers. This sort of error can occur if there's a holdup with the dimensions, or the mod is trying to register a dimension twice.
