### ISSUE TITLE
Tardis shell duplicating on fabric server

### ISSUE THREAD

**Issue by Toasterflame** [WhoCraft/TardisRefined#152]
### Issue description

when using the tardis on a fabric server. the outside shell duplicates in the original position. this happens every time so far.
the server we are using has other mods. but this only occurs inside of the server not on a singleplayer game

### Steps to reproduce

run a fabric server on 1.19.2
fly the tardis (successfully or unsuccessfully)
done

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

fabric 0.14.21-1.19.2

### Tardis Refined version

v1.0

**Comment by pseudoble** [comment]
This just happened to me on a forge server. The glitched shell was only partially rendering and I could not remove it but stepping through it still teleported me to my real TARDIS. I'm on a 1.19.2 forge server

**Comment by Toasterflame** [comment]
> This just happened to me on a forge server. The glitched shell was only partially rendering and I could not remove it but stepping through it still teleported me to my real TARDIS. I'm on a 1.19.2 forge server

yup exactly the same thing im experiencing
sucks cos this mod is pretty damn cool, waiting for a fix to come hopefully

**Comment by auroricdragon** [comment]
Same here!

**Comment by AnonymouseCow** [comment]
> This just happened to me on a forge server. The glitched shell was only partially rendering and I could not remove it but stepping through it still teleported me to my real TARDIS. I'm on a 1.19.2 forge server

Same! The only way to get rid of it is to stand inside of it, on top of the hitbox on the bottom and run /fill ~ ~ ~ ~ ~ ~ air

**Comment by 50ap5ud5** [comment]
Thank you. We are able to reproduce this issue and will work on resolving it.
